### ISSUE TITLE
Allow user to specify environment in provided script

### ISSUE THREAD

**Issue by LingForCC** [ringcentral/ringcentral-js-widget#12]
Now user is allowed to specify AppKey and AppSecret in embed script. I am wondering whether we should also allow user to specify environment so that user could switch between Production/Sandbox environment.

**Comment by changbenny** [comment]
I agree, add an options in `<rc-phone>` tag will be good.

**Comment by changbenny** [comment]
Done. Need to add documents about the options of `<rc-phone>` tag.
