### ISSUE TITLE
what is the required permissions and Platform Type needed to use the ringcentral-js-widget?

### ISSUE THREAD

**Issue by mgw2007** [ringcentral/ringcentral-js-widget#17]

**Comment by LingForCC** [comment]
You just need a valid RingCentral account to use the widgets.

**Comment by mgw2007** [comment]
Hi
to use this widget
<rc-widget
    tag=rc-phone
    first-level=dial-pad,time-line 
    width=250
    height=400
    key=YOUR_APP_KEY
    secret=YOUR_APP_SECRET
    env=sandbox
    position=fixed>
</rc-widget>
my question is about YOUR_APP_KEY and YOUR_APP_SECRET 
what Is the required permissions and Platform Type for the app ?

**Comment by LingForCC** [comment]
@mgw2007 This is a widget lib built based on [RingCentral Connect Platform](https://developer.ringcentral.com/). You can get corresponding AppKey/AppSecret once you become a RingCentral developer.
