### ISSUE TITLE
import PropTypes from react is deprecated in version 15

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-js-widget#221]
`import { PropTypes } from react` is deprecated in react version 15.

warning.js: Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

**Comment by LingForCC** [comment]
@u9520107  Is this what you mentioned several days ago?

**Comment by u9520107** [comment]
Yes, we should upgrade react and make changes accordingly. This should be quite simple.
