### ISSUE TITLE
Upgrade webpack to version 2

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-js-widget#238]
webpack version 2 has been released for several months. It's time to upgrade.

**Comment by u9520107** [comment]
Yes, we'd love to upgrade. Unfortunately there are things that doesn't work well with webpack 2 at the moment. We'll be discussing these in more details and try to resolve them so that we can support using webpack 2 without various work arounds.

**Comment by tylerlong** [comment]
PR created: https://github.com/ringcentral/ringcentral-js-widget/pull/240
