### ISSUE TITLE
Can only see part of the hang up button when making a call

### ISSUE THREAD

**Issue by tylerlong** [ringcentral/ringcentral-js-widget#294]
When the page is wide, only part of the hang up button is displayed. If the page is wider, the button is completed out of view which makes it impossible to hang up.

Expected behavior: the widget should auto adjust its height so it never exceeds the browser window height.

![partial-button-issue](https://user-images.githubusercontent.com/733544/28305848-d88a9fce-6bcf-11e7-906a-3f413525a67e.gif)

**Comment by PacoVu** [comment]
How could you get this kind of menu bar? I just try the code and see only the 4 basic items on the menu [Dial pad, Phone (Active Calls), History, Settings]

**Comment by u9520107** [comment]
@PacoVu Some of the menu items will only show up if the appKey and the extension you login with has the right permissions. For example, you may need to add Read Messages/Edit Messages permission and use an extension with message support to see the messages related tabs.

**Comment by u9520107** [comment]
@embbnux Consider implementing the call controls the way we implemented the dial buttons. The way the buttons are scaled is different, and should be able to at least prevent them are being rendered out of bound.

**Comment by embbnux** [comment]
Yeah, I am doing this.
