### ISSUE TITLE
Error in console when pressing 'Enter' with an invalid number

### ISSUE THREAD

**Issue by LingForCC** [ringcentral/ringcentral-js-widget#4]
**Version**

0.1.0

**Actual Behavior**

Error in console when pressing 'Enter' with an invalid number
```
VM940:131 Uncaught TypeError: Cannot read property 'props' of undefined
```

**Expected Behavior**
No error message shown in console

**How to reproduce**

- Login the app and switch to web phone
- Input an invalid number
- Press 'Enter'
- Error shown in console

**Comment by changbenny** [comment]
Fiexed.
