### ISSUE TITLE
Phone Number Input in Web Phone pops up unexpected number when minimizing the app

### ISSUE THREAD

**Issue by LingForCC** [ringcentral/ringcentral-js-widget#5]
**Version**
0.1.0

**Actual Behavior**
Phone Number Input in Web Phone pops up unexpected number when minimizing the app

**Expected Behavior**
Input should stay as what it is when minimizing or normalizing

**How to Reproduce**

- Login app and switch to Web Phone
- Use Phone Number Input to search for a contact and press 'Enter' to choose a specific contact
- Modify number in Phone Number Input to any value
- Minimize the app and the Phone Number Input pops up the number of last selected contact

**Comment by changbenny** [comment]
fixed.
