### ISSUE TITLE
Add logout capability

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-js-widget#6]
Support manual logout so users can log out of the widget if they choose which can be for security or changing users, similar to RC Google Chrome integration.

**Comment by changbenny** [comment]
Fixed, the logout button now at top right corner:
![screen shot 2016-06-01 at 4 14 57 pm](https://cloud.githubusercontent.com/assets/3777138/15702693/04bed8fe-2814-11e6-8606-edfb466129f6.png)
The icon is a little bit confusing now.

**Comment by grokify** [comment]
What about using the FontAwesome `sign-out` icon?

http://fontawesome.io/icon/sign-out/
