### ISSUE TITLE
Update dialpad during call to be consistent

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-js-widget#7]
The dialpad when dialing shows all circles for digit buttons but after a call is connected it shows a square button for `0` only. Make the `0` button a circle to be consistent with the rest of the buttons.

<img width="240" alt="screen shot 2016-05-31 at 9 29 42 pm" src="https://cloud.githubusercontent.com/assets/209872/15698221/3047b128-2777-11e6-815f-0c77b8c8f32b.png">

**Comment by changbenny** [comment]
Fixed.
