### ISSUE TITLE
Show warning message in standard way if the SMS content is empty when sending

### ISSUE THREAD

**Issue by LingForCC** [ringcentral/ringcentral-js-widget#92]
We need to show warning message by using standard way.

![image](https://cloud.githubusercontent.com/assets/5373202/23554698/272253dc-0061-11e7-9bd7-22a19ded37d2.png)

**Comment by LingForCC** [comment]
I think we can add Integration Test for this scenario.

**Comment by LingForCC** [comment]
Fixed with #102

**Comment by LingForCC** [comment]
@embbnux Looks like Integration Test is not added.

**Comment by embbnux** [comment]
There are two verfications on text empty before, one is browser required feature and one is standard way.
There are Integration Test test on text empty with standard way.  
But Integration Test don't test browser way. Now the browser way is removed.

**Comment by LingForCC** [comment]
ok. It makes sense.
