### ISSUE TITLE
Show 'International SMS is not supported' error returned from server

### ISSUE THREAD

**Issue by LingForCC** [ringcentral/ringcentral-js-widget#93]
**How to reproduce**
1. Login with an US number which doesn't support international SMS
2. Set dialing plan to UK
3. Try to send sms to a number without country code from a US number

**Actual Behavior**
It shows 'Something wrong happens when sending SMS'

**Expected Behavior**
It shows 'International SMS is not supported'

**Comment by LingForCC** [comment]
I think we can also add Integration Test for this scenario.

**Comment by embbnux** [comment]
PR In Commons: [Message error handle](https://github.com/ringcentral/ringcentral-js-integration-commons/pull/221) fix this problem.

**Comment by embbnux** [comment]
fixed
