### ISSUE TITLE
Should we ignore subsequent alert messages?

### ISSUE THREAD

**Issue by LingForCC** [ringcentral/ringcentral-js-widget#97]
@embbnux @u9520107 
When the message content is empty and I try to click the 'Send' button for several times, the alert messages will show up for several times looks like below

![image](https://cloud.githubusercontent.com/assets/5373202/23558381/55629ae2-006e-11e7-925b-9c5a9b9fb39a.png)

Should we ignore subsequent alert message so that it shows only one before it is dismissed?

**Comment by u9520107** [comment]
We do have this feature already. Notice the allowDuplicate parameter in the alert function, passing false would make the alert module check if the same message is already in display.
```javascript
 @proxify
  async alert({
    message,
    payload,
    level = alertLevels.info,
    ttl = this._ttl,
    allowDuplicates = true,
  }) {
```

**Comment by LingForCC** [comment]
Looks good. Let's close this.
