### ISSUE TITLE
Why is there a 'Loading' at the bottom of the App?

### ISSUE THREAD

**Issue by LingForCC** [ringcentral/ringcentral-js-widget#98]
![image](https://cloud.githubusercontent.com/assets/5373202/23558466/b27fe4e6-006e-11e7-97f2-a5c0ffa615ce.png)

**Comment by embbnux** [comment]
It's used to show loading when user scroll to bottom and loading next page.
it may be a bug from you screenshot, I will fix it soon

**Comment by LingForCC** [comment]
Fixed with #107
